### ISSUE TITLE
write instructions for installing project for PC/Linux

### ISSUE THREAD

**Issue by svmatthews** [cugos/drop-n-chop#94]
https://github.com/cugos/drop-n-chop/wiki/Installing-the-Project only exists as Mac

**Comment by mapsam** [comment]
@thedeb any interest in this?

**Comment by keum** [comment]
mapsam, folks are here going to meet in two weeks to start writing out doc for PC for installation..do you have a good starting point for PC?

**Comment by mapsam** [comment]
Good question. I don't have a PC to test on, but might be able to spin up a virtual machine to see what happens. Could you ping me next week in this issue so we can talk more details?

**Comment by keum** [comment]
oh, it's folks from KC, debbie, paul and few others. i think frank, another KC person tried to install drop during spring fling and had hell of time but with something that started. so we may start from that...will sure to ping you if we get some questions for sure. looking forward to catch up soon when you back to SEA.

**Comment by thedeb** [comment]
Ya, I'm interested. :)

**Comment by mapsam** [comment]
Great! The dependencies are a bit different now than they were at the spring fling, but imagine there are problems abound. Looking forward to hearing how it goes :smile:

**Comment by npeihl** [comment]
I've had trouble with `node-gyp` build errors when running `npm install` on Windows x64. [This solution](http://stackoverflow.com/questions/21562038/node-gyp-build-error-windows-x64) fixed it for me. I also remember some folks having trouble with `sass` at the Spring Fling because of the Ruby dependency. But I don't think Ruby is a dependency anymore?

**Comment by mapsam** [comment]
Correct. No more ruby dependency.

**Comment by thedeb** [comment]
Hey Sam. We're working on installation instructions for Windows. Should we add notes in-line in the existing INSTALLATION.md file or create a new INSTALLATION_WIN.md?

**Comment by mapsam** [comment]
I'd add in-line, just add a 

# Windos Instructions

line! thanks :smile:

**Comment by thedeb** [comment]
Thanks!

**Comment by thedeb** [comment]
Paul is making notes. We're having problems: 

module.js:339

**Comment by mapsam** [comment]
yay problems, I'd load this issue with full copies of your terminal errors

**Comment by thedeb** [comment]
Ya, I just realized there's not much point in my re-typing one line when Paul's got the full stack trace.  We'll get it in here when we're done with our session.

**Comment by mccombsp-kingco** [comment]
Trying to install dropchop on windows 7,
Got several warnings from npm install. Then gulp build:prod errored out on readable-stream/transform which was in the npm warning list.

Warnings from npm install on my computer - paul mccombs:
========================================================

C:\Users\mccombsp\Documents\GitHub\dropchop>npm install
npm WARN unmet dependency C:\Users\mccombsp\Documents\GitHub\dropchop\node_modules\topojson\node_modules\d3-

geo-projection\node_modules\brfs\node_modules\static-module\node_modules
\static-eval requires escodegen@'~0.0.24' but will load
npm WARN unmet dependency C:\Users\mccombsp\Documents\GitHub\dropchop\node_modules\topojson\node_modules\d3-

geo-projection\node_modules\brfs\node_modules\static-module\node_modules
\escodegen,
npm WARN unmet dependency which is version 1.3.3
npm WARN unmet dependency C:\Users\mccombsp\Documents\GitHub\dropchop\node_modules\browserify\node_modules

\module-deps requires readable-stream@'^1.1.13' but will load
npm WARN unmet dependency C:\Users\mccombsp\Documents\GitHub\dropchop\node_modules\browserify\node_modules

\readable-stream,
npm WARN unmet dependency which is version 2.0.4
npm WARN unmet dependency C:\Users\mccombsp\Documents\GitHub\dropchop\node_modules\gulp-jshint\node_modules

\gulp-util requires through2@'^2.0.0' but will load
npm WARN unmet dependency C:\Users\mccombsp\Documents\GitHub\dropchop\node_modules\gulp-jshint\node_modules

\through2,
npm WARN unmet dependency which is version 0.6.5

Error from gulp build:prod
==========================

C:\Users\mccombsp\Documents\GitHub\dropchop>gulp build:prod
module.js:339
    throw err;
    ^

Error: Cannot find module 'readable-stream/transform'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\mccombsp\Documents\GitHub\dropchop\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\through2.js:1:79)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

**Comment by mapsam** [comment]
Npm is now in `3.x`, which includes a ton of fixes for PC. Might be worth picking this up again.

**Comment by thedeb** [comment]
+1
